<?php

namespace Ihsw\LedgerBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * EntryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EntryRepository extends EntityRepository
{
	public function findAll()
	{
		return $this->createQueryBuilder("e")
			->select("e")
			->orderBy("e.occurredAt", "ASC")
			->getQuery()
			->getResult();
	}
}
