Ihsw\LedgerBundle\Entity\Entry:
    type: entity
    table: null
    repositoryClass: Ihsw\LedgerBundle\Entity\EntryRepository
    fields:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
        occurredAt:
            type: date
            column: occurred_at
    oneToMany:
        entryItems:
            targetEntity: EntryItem
            mappedBy: entry
    lifecycleCallbacks: {  }
