Ihsw\LedgerBundle\Entity\EntryItem:
    type: entity
    table: null
    repositoryClass: Ihsw\LedgerBundle\Entity\EntryItemRepository
    fields:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
        cost:
            type: decimal
            precision: 13
            scale: 3 # a billion dollars, plus digits after the decimal
        quantity:
            type: integer
    manyToOne:
        entry:
            targetEntity: Entry
            inversedBy: entryItems
            joinColumn:
                name: entry_id
                referencedColumnName: id
                nullable: false
        item:
            targetEntity: Item
            inversedBy: entryItems
            joinColumn:
                name: item_id
                referencedColumnName: id
                nullable: false
    lifecycleCallbacks: {  }
