Ihsw\LedgerBundle\Entity\Item:
    type: entity
    table: null
    repositoryClass: Ihsw\LedgerBundle\Entity\ItemRepository
    fields:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
        name:
            type: string
            length: 255
    oneToMany:
        entryItems:
            targetEntity: EntryItem
            mappedBy: item
    manyToOne:
        collection:
            targetEntity: Collection
            inversedBy: items
            joinColumn:
                name: collection_id
                referencedColumnName: id
                nullable: false
    lifecycleCallbacks: {  }
