# misc
home:
    pattern:  /
    defaults: { _controller: IhswLedgerBundle:Default:index }
    options:
        expose: true
home_summary:
    pattern: /summary
    defaults: { _controller: IhswLedgerBundle:Default:summary }
    options:
        expose: true

# collections
collections:
    pattern: /collections
    defaults: { _controller: IhswLedgerBundle:Collection:index }
    methods: [GET]
    options:
        expose: true
collection_create:
    pattern: /collections
    defaults: { _controller: IhswLedgerBundle:Collection:create }
    methods: [POST]
    options:
        expose: true
collection_delete:
    pattern: /collection/{collectionId}
    defaults: { _controller: IhswLedgerBundle:Collection:destroy }
    methods: [DELETE]
    options:
        expose: true
collection_show:
    pattern: /collection/{collectionId}
    defaults: { _controller: IhswLedgerBundle:Collection:show }
    methods: [GET]
    options:
        expose: true
collection_update:
    pattern: /collection/{collectionId}
    defaults: { _controller: IhswLedgerBundle:Collection:update }
    methods: [PUT]
    options:
        expose: true

# items
item_create:
    pattern: /collection/{collectionId}/items
    defaults: { _controller: IhswLedgerBundle:Item:create }
    methods: [POST]
    options:
        expose: true
item_delete:
    pattern: /item/{itemId}
    defaults: { _controller: IhswLedgerBundle:Item:destroy }
    methods: [DELETE]
    options:
        expose: true
item_show:
    pattern: /item/{itemId}
    defaults: { _controller: IhswLedgerBundle:Item:show }
    methods: [GET]
    options:
        expose: true
item_update:
    pattern: /item/{itemId}
    defaults: { _controller: IhswLedgerBundle:Item:update }
    methods: [PUT]
    options:
        expose: true

# entries
entries:
    pattern: /entries
    defaults: { _controller: IhswLedgerBundle:Entry:index }
    methods: [GET]
    options:
        expose: true
entry_create:
    pattern: /entries
    defaults: { _controller: IhswLedgerBundle:Entry:create }
    methods: [POST]
    options:
        expose: true
entry_delete:
    pattern: /entry/{entryId}
    defaults: { _controller: IhswLedgerBundle:Entry:destroy }
    methods: [DELETE]
    options:
        expose: true
entry_show:
    pattern: /entry/{entryId}
    defaults: { _controller: IhswLedgerBundle:Entry:show }
    methods: [GET]
    options:
        expose: true
entry_update:
    pattern: /entry/{entryId}
    defaults: { _controller: IhswLedgerBundle:Entry:update }
    methods: [PUT]
    options:
        expose: true

# entryitems
entryitem_create:
    pattern: /entry/{entryId}/entryitems
    defaults: { _controller: IhswLedgerBundle:EntryItem:create }
    methods: [POST]
    options:
        expose: true
entryitem_delete:
    pattern: /entryitem/{entryItemId}
    defaults: { _controller: IhswLedgerBundle:EntryItem:destroy }
    methods: [DELETE]
    options:
        expose: true
entryitem_show:
    pattern: /entryitem/{entryItemId}
    defaults: { _controller: IhswLedgerBundle:EntryItem:show }
    methods: [GET]
    options:
        expose: true
entryitem_update:
    pattern: /entryitem/{entryItemId}
    defaults: { _controller: IhswLedgerBundle:EntryItem:update }
    methods: [PUT]
    options:
        expose: true
entryitem_update_item:
    pattern: /entryitem/{entryItemId}/update-item
    defaults: { _controller: IhswLedgerBundle:EntryItem:updateItem }
    methods: [PUT]
    options:
        expose: true