parameters:
#    ihsw_ledger.example.class: Ihsw\LedgerBundle\Example

services:
    my.param_converter:
        class: Ihsw\LedgerBundle\ParamConverter
        tags:
            - { name: request.param_converter }
        arguments: [@service_container]