<?php

namespace Ihsw\LedgerBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * EntryItemRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EntryItemRepository extends EntityRepository
{
}
