parameters:
#    ihsw_ledger.example.class: Ihsw\LedgerBundle\Example

services:
    ihsw.event_listener:
        class: Ihsw\LedgerBundle\EventListener
        tags:
            - { name: kernel.event_listener, event: console.command, method: onConsoleCommand }
            - { name: kernel.event_listener, event: console.terminate, method: onConsoleTerminate }
        arguments: [@service_container, @controller_resolver]